name = "CausalTrees"
uuid = "036332e5-867c-425c-9ec5-a168d08a340a"
authors = ["oizin <fitzgeraldoisin@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
